blank_issues_enabled: false
contact_links:
  - name: Vue.js Paris Meetup
    url: https://www.meetup.com/vuejs-paris/
  - name: Planning
    url: https://github.com/orgs/Vue-js-Paris/projects/1
    about: Planning des meetups
